version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - cassandra
      - redis
    environment:
      - CASSANDRA_HOST=cassandra
      - REDIS_HOST=redis

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"

#  cassandra1:
#    image: cassandra:latest
#    container_name: cassandra1
#    ports:
#      - "9042:9042"
#    environment:
#      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
#      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
#    volumes:
#      - ./cassandra1/data:/var/lib/cassandra
#      - ./cassandra1/config:/etc/cassandra
#
#  cassandra2:
#    image: cassandra:latest
#    container_name: cassandra2
#    ports:
#      - "9043:9042"
#    environment:
#      - CASSANDRA_SEEDS=cassandra1
#      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
#      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
#    volumes:
#      - ./cassandra2/data:/var/lib/cassandra
#      - ./cassandra2/config:/etc/cassandra
#
#  cassandra3:
#    image: cassandra:latest
#    container_name: cassandra3
#    ports:
#      - "9044:9042"
#    environment:
#      - CASSANDRA_SEEDS=cassandra1
#      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
#      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
#    volumes:
#      - ./cassandra3/data:/var/lib/cassandra
#      - ./cassandra3/config:/etc/cassandra

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
