version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - cassandra
      - redis
    environment:
      - CASSANDRA_HOST=cassandra
      - REDIS_HOST=redis

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
